//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrganizationType = &struct {
	Ie  postgres.StringExpression
	Llc postgres.StringExpression
	Jsc postgres.StringExpression
}{
	Ie:  postgres.NewEnumValue("IE"),
	Llc: postgres.NewEnumValue("LLC"),
	Jsc: postgres.NewEnumValue("JSC"),
}
