//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BidVersions = newBidVersionsTable("public", "bid_versions", "")

type bidVersionsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	BidID           postgres.ColumnInteger
	Name            postgres.ColumnString
	Description     postgres.ColumnString
	Status          postgres.ColumnString
	TenderID        postgres.ColumnInteger
	OrganizationID  postgres.ColumnString
	CreatorUsername postgres.ColumnString
	Version         postgres.ColumnInteger
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BidVersionsTable struct {
	bidVersionsTable

	EXCLUDED bidVersionsTable
}

// AS creates new BidVersionsTable with assigned alias
func (a BidVersionsTable) AS(alias string) *BidVersionsTable {
	return newBidVersionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BidVersionsTable with assigned schema name
func (a BidVersionsTable) FromSchema(schemaName string) *BidVersionsTable {
	return newBidVersionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BidVersionsTable with assigned table prefix
func (a BidVersionsTable) WithPrefix(prefix string) *BidVersionsTable {
	return newBidVersionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BidVersionsTable with assigned table suffix
func (a BidVersionsTable) WithSuffix(suffix string) *BidVersionsTable {
	return newBidVersionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBidVersionsTable(schemaName, tableName, alias string) *BidVersionsTable {
	return &BidVersionsTable{
		bidVersionsTable: newBidVersionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newBidVersionsTableImpl("", "excluded", ""),
	}
}

func newBidVersionsTableImpl(schemaName, tableName, alias string) bidVersionsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		BidIDColumn           = postgres.IntegerColumn("bid_id")
		NameColumn            = postgres.StringColumn("name")
		DescriptionColumn     = postgres.StringColumn("description")
		StatusColumn          = postgres.StringColumn("status")
		TenderIDColumn        = postgres.IntegerColumn("tender_id")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		CreatorUsernameColumn = postgres.StringColumn("creator_username")
		VersionColumn         = postgres.IntegerColumn("version")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{IDColumn, BidIDColumn, NameColumn, DescriptionColumn, StatusColumn, TenderIDColumn, OrganizationIDColumn, CreatorUsernameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{BidIDColumn, NameColumn, DescriptionColumn, StatusColumn, TenderIDColumn, OrganizationIDColumn, CreatorUsernameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return bidVersionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		BidID:           BidIDColumn,
		Name:            NameColumn,
		Description:     DescriptionColumn,
		Status:          StatusColumn,
		TenderID:        TenderIDColumn,
		OrganizationID:  OrganizationIDColumn,
		CreatorUsername: CreatorUsernameColumn,
		Version:         VersionColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
