//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Bid = Bid.FromSchema(schema)
	BidVersions = BidVersions.FromSchema(schema)
	BidVotes = BidVotes.FromSchema(schema)
	Employee = Employee.FromSchema(schema)
	Organization = Organization.FromSchema(schema)
	OrganizationResponsible = OrganizationResponsible.FromSchema(schema)
	Review = Review.FromSchema(schema)
	Tender = Tender.FromSchema(schema)
	TenderVersions = TenderVersions.FromSchema(schema)
}
