//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TenderVersions = newTenderVersionsTable("public", "tender_versions", "")

type tenderVersionsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	TenderID        postgres.ColumnInteger
	Name            postgres.ColumnString
	Description     postgres.ColumnString
	ServiceType     postgres.ColumnString
	Status          postgres.ColumnString
	OrganizationID  postgres.ColumnString
	CreatorUsername postgres.ColumnString
	Version         postgres.ColumnInteger
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TenderVersionsTable struct {
	tenderVersionsTable

	EXCLUDED tenderVersionsTable
}

// AS creates new TenderVersionsTable with assigned alias
func (a TenderVersionsTable) AS(alias string) *TenderVersionsTable {
	return newTenderVersionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenderVersionsTable with assigned schema name
func (a TenderVersionsTable) FromSchema(schemaName string) *TenderVersionsTable {
	return newTenderVersionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenderVersionsTable with assigned table prefix
func (a TenderVersionsTable) WithPrefix(prefix string) *TenderVersionsTable {
	return newTenderVersionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenderVersionsTable with assigned table suffix
func (a TenderVersionsTable) WithSuffix(suffix string) *TenderVersionsTable {
	return newTenderVersionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenderVersionsTable(schemaName, tableName, alias string) *TenderVersionsTable {
	return &TenderVersionsTable{
		tenderVersionsTable: newTenderVersionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newTenderVersionsTableImpl("", "excluded", ""),
	}
}

func newTenderVersionsTableImpl(schemaName, tableName, alias string) tenderVersionsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		TenderIDColumn        = postgres.IntegerColumn("tender_id")
		NameColumn            = postgres.StringColumn("name")
		DescriptionColumn     = postgres.StringColumn("description")
		ServiceTypeColumn     = postgres.StringColumn("service_type")
		StatusColumn          = postgres.StringColumn("status")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		CreatorUsernameColumn = postgres.StringColumn("creator_username")
		VersionColumn         = postgres.IntegerColumn("version")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{IDColumn, TenderIDColumn, NameColumn, DescriptionColumn, ServiceTypeColumn, StatusColumn, OrganizationIDColumn, CreatorUsernameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{TenderIDColumn, NameColumn, DescriptionColumn, ServiceTypeColumn, StatusColumn, OrganizationIDColumn, CreatorUsernameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return tenderVersionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		TenderID:        TenderIDColumn,
		Name:            NameColumn,
		Description:     DescriptionColumn,
		ServiceType:     ServiceTypeColumn,
		Status:          StatusColumn,
		OrganizationID:  OrganizationIDColumn,
		CreatorUsername: CreatorUsernameColumn,
		Version:         VersionColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
