//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OrganizationType string

const (
	OrganizationType_Ie  OrganizationType = "IE"
	OrganizationType_Llc OrganizationType = "LLC"
	OrganizationType_Jsc OrganizationType = "JSC"
)

func (e *OrganizationType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "IE":
		*e = OrganizationType_Ie
	case "LLC":
		*e = OrganizationType_Llc
	case "JSC":
		*e = OrganizationType_Jsc
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OrganizationType enum")
	}

	return nil
}

func (e OrganizationType) String() string {
	return string(e)
}
