//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TenderVersions struct {
	ID              uuid.UUID `sql:"primary_key"`
	TenderID        *int32
	Name            string
	Description     *string
	ServiceType     string
	Status          *string
	OrganizationID  *uuid.UUID
	CreatorUsername string
	Version         *int32
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}
